"""
Validation & Correction Agent

Validates SQL syntax and safety using SQLGlot.
Corrects broken SQL using the LLM when execution or validation fails.
"""

import sqlglot
from langchain_core.messages import SystemMessage, HumanMessage

from core.llm import get_llm
from features.validation_correction.prompt import (
    VALIDATION_CORRECTION_SYSTEM_PROMPT,
    VALIDATION_CORRECTION_HUMAN_TEMPLATE,
)


from schemas.validation import SQLCorrectionResult
from features.validation_correction.repair_engine import repair_sql_clause
from features.validation_correction.error_classifier import classify_sql_error


def validate_sql_safety(sql: str, dialect: str = "postgres") -> bool:
    """
    Parses the SQL query with SQLGlot to ensure it is syntactically valid
    and strictly read-only (no DROP, DELETE, ALTER, UPDATE, INSERT, etc.).

    Args:
        sql: The raw SQL query string.
        dialect: SQL dialect (e.g., 'postgres', 'sqlite') to parse.

    Returns:
        True if the SQL is safe and valid.

    Raises:
        ValueError: If the SQL contains unsafe statements or syntax errors.
    """
    try:
        # sqlglot.parse returns a list of AST expressions
        parsed_statements = sqlglot.parse(sql, read=dialect)
    except sqlglot.errors.ParseError as e:
        raise ValueError(f"SQL Syntax Error: {e}")

    if not parsed_statements:
        raise ValueError("Empty SQL query provided.")

    allowed_expressions = (sqlglot.exp.Select, )

    for stmt in parsed_statements:
        if stmt is None:
            continue
        # Ensure that every parsed statement is a SELECT query
        if not isinstance(stmt, allowed_expressions):
            raise ValueError(
                f"Unsafe or unauthorized SQL statement detected: {type(stmt).__name__}. "
                "Only SELECT statements are allowed."
            )

    return True


def correct_sql(failed_sql: str, error_message: str, schema: str, original_query: str) -> SQLCorrectionResult:
    """
    Calls the LLM to fix a broken SQL query based on the schema and error message.
    Tries surgical clause repair first, falling back to full query regeneration.

    Args:
        failed_sql: The failed SQL string.
        error_message: The error generated by the database or validator.
        schema: The database schema string.
        original_query: The natural language intent query.

    Returns:
        A SQLCorrectionResult Pydantic model containing the thought process and corrected SQL.
    """
    if not failed_sql or not error_message or not schema:
        raise ValueError("failed_sql, error_message, and schema must be provided.")

    import logging
    import re
    import json
    logger = logging.getLogger(__name__)

    # Diagnose the SQL error using the formal taxonomy engine
    classification = classify_sql_error(
        failed_sql=failed_sql,
        error_message=error_message,
        schema=schema,
        original_query=original_query
    )

    # Try AST-based surgical clause repair first
    try:
        repaired_sql = repair_sql_clause(
            failed_sql=failed_sql,
            error_message=error_message,
            schema=schema,
            original_query=original_query,
            classification=classification
        )
        if repaired_sql:
            logger.info("Successfully repaired SQL using surgical clause-level AST grafting.")
            return SQLCorrectionResult(
                thought_process="Surgically repaired SQL using clause-level AST grafting.",
                corrected_sql=repaired_sql,
                error_classification=classification
            )
    except Exception as re_err:
        logger.warning(f"AST-based surgical clause repair failed: {re_err}. Falling back to full query correction.")

    logger.info("Executing taxonomy-aware full SQL query regeneration fallback...")
    llm = get_llm()

    human_content = VALIDATION_CORRECTION_HUMAN_TEMPLATE.format(
        schema=schema.strip(),
        query=original_query.strip(),
        failed_sql=failed_sql.strip(),
        error_message=error_message.strip(),
        error_category=classification.category,
        error_subcategory=classification.subcategory,
        error_description=classification.description,
        suggested_fix=classification.suggested_fix
    )

    messages = [
        SystemMessage(content=VALIDATION_CORRECTION_SYSTEM_PROMPT),
        HumanMessage(content=human_content),
    ]

    response = llm.invoke(messages)
    
    # Strip markdown code blocks if LLM adds them
    from core.llm import extract_text
    content = extract_text(response).strip()
    logger.debug(f"Raw LLM response for SQL correction:\n{content}")

    # Extract JSON block deterministically
    match = re.search(r"(\{.*\})", content, re.DOTALL)
    if not match:
        logger.error(f"Failed to find JSON block in LLM response: {content}")
        raise ValueError("The SQL correction agent did not output a valid JSON correction block.")

    json_str = match.group(1)
    data = json.loads(json_str)

    # Validate against the Pydantic SQLCorrectionResult model
    if hasattr(SQLCorrectionResult, "model_validate"):
        result = SQLCorrectionResult.model_validate(data)
    else:
        result = SQLCorrectionResult.parse_obj(data)

    result.error_classification = classification

    logger.info(
        f"SQL correction completed successfully. "
        f"Thought Process: {result.thought_process}"
    )
    return result

