import streamlit as st
import requests
import pandas as pd

API_URL = "http://localhost:8000/api/v1/ask"

# 1. Page Configuration
st.set_page_config(page_title="DataSense AI", page_icon="?", layout="wide")

# 2. Custom CSS to make it look like a clean AI app (hide Streamlit branding)
st.markdown("""
    <style>
        #MainMenu {visibility: hidden;}
        footer {visibility: hidden;}
        header {visibility: hidden;}
        .block-container {
            padding-top: 2rem;
            padding-bottom: 2rem;
            max-width: 48rem; /* ChatGPT-like width */
        }
        .stChatMessage {
            padding: 1rem;
            border-radius: 0.5rem;
        }
    </style>
""", unsafe_allow_html=True)

# 3. Sidebar (Like ChatGPT's left panel)
with st.sidebar:
    st.title("? DataSense AI")
    st.markdown("Navigate your database using natural language.")
    st.divider()
    
    st.markdown("### ?? Example Queries")
    st.info("What is the total revenue generated by each product category, ordered from highest to lowest?")
    st.info("Which city has the highest number of premium users?")
    st.info("Show me the names of products that have an average rating above 4.5 but have less than 50 items in stock.")
    
    st.divider()
    st.markdown("### ??? Architecture")
    st.caption("- **Orchestration**: LangGraph")
    st.caption("- **LLM**: Gemini-2.5-Flash")
    st.caption("- **Database**: PostgreSQL (E-Commerce Schema)")

# 4. Main Chat Header
st.title("Chat with your Database")
st.markdown("Ask anything in plain English, and the AI agent flow will convert it, validate it, and fetch your data.")

# 5. Session State for Chat History
if "messages" not in st.session_state:
    st.session_state.messages = [
        {"role": "assistant", "content": "Hello! I am your AI SQL Agent. How can I help you analyze your data today?"}
    ]

# 6. Render Chat History
for msg in st.session_state.messages:
    with st.chat_message(msg["role"], avatar="✨" if msg["role"] == "assistant" else "👤"):
        st.markdown(msg["content"])
        
        # Render AI's rich data if it exists in history
        if msg["role"] == "assistant" and "data" in msg:
            with st.expander("🛠️ View AI Thought Process & SQL"):
                st.caption(f"**Refined Intent:** {msg['data'].get('refined_query', 'N/A')}")
                st.code(msg['data'].get('sql_query', '-- No SQL returned'), language="sql")
                if msg["data"].get("error"):
                    st.error(msg["data"]["error"])

            results = msg["data"].get("results")
            if results:
                st.dataframe(pd.DataFrame(results))

# 7. Chat Input (Fixed at bottom)
if prompt := st.chat_input("Message DataSense AI..."):
    # Append User Message
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user", avatar="👤"):
        st.markdown(prompt)

    # Process and Append Assistant Message
    with st.chat_message("assistant", avatar="✨"):
        with st.spinner("Analyzing schema and generating SQL..."):
            try:
                response = requests.post(API_URL, json={"query": prompt})
                response.raise_for_status()
                data = response.json()
                
                error_msg = data.get("error")
                sql = data.get("sql_query")
                results = data.get("results")

                # Format the text answer
                if error_msg:
                    answer_text = f"I encountered an error trying to process that query. Please see the details below."
                elif results is not None:
                    answer_text = f"Here is the data you requested! (Found {len(results)} records)"
                else:
                    answer_text = "I parsed the query, but no results were returned from the database."

                st.markdown(answer_text)

                # Show the AI's internal workings (like ChatGPT's "Analyzed" dropdown)
                with st.expander("??? View AI Thought Process & SQL"):
                    st.caption(f"**Refined Intent:** {data.get('refined_query', 'N/A')}")
                    st.code(sql if sql else "-- No SQL generated", language="sql")
                    if error_msg:
                        st.error(error_msg)

                # Show the table
                if results:
                    st.dataframe(pd.DataFrame(results), use_container_width=True)

                # Save to history
                st.session_state.messages.append({
                    "role": "assistant",
                    "content": answer_text,
                    "data": data
                })

            except requests.exceptions.RequestException as e:
                error_text = f"An API connection error occurred: {e}"
                st.error(error_text)
                st.session_state.messages.append({
                    "role": "assistant",
                    "content": error_text
                })
